---
# tasks file for setup-apache-role
- name: install httpd
  yum:
    name: "{{ httpd_package_name }}"
    state: installed
  when : ansible_os_family == "RedHat"
  notify: start httpd service

- name: install apache2
  apt:
    name: "{{ apache2_package_name }}"
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: copy index.html 
  copy:
    src: index.html
    dest: /var/www/html
    mode: 0666

