---
- name: playbook
  hosts: all
  become: true
  tasks:
  - name: service stop
    service:
      name: httpd
      state: stopped

  - name: uninstall httpd
    yum:
      name: httpd
      state: removed
